// This file is generated by Slice Machine. Update with care!

import MeuPosts from './MeuPosts';
import Meupost from './Meupost';

export {
	MeuPosts,
	Meupost,
};

export const components = {
	meu_posts: MeuPosts,
	meupost: Meupost,
};
